rootProject.name = "wiki-agent"
include("callgraph-plugin")
include(":context")
include(":config")
include(":github")
include(":rag")
include(":confluence")
include(":jira")
include(":llm")
include(":search")
include(":onboarding")
include(":knowledge")
